#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR="$ROOT/.agent-vendor"
LOCK="$ROOT/.agent-deps.lock"

PSTACK_REF="${PSTACK_REF:-main}"
PSTACK_CROSS_REF="${PSTACK_CROSS_REF:-main}"
MATT_REF="${MATT_REF:-main}"

LOCAL_ONLY=0
INSTALL_PSTACK=1
INSTALL_CROSS_PSTACK=1
INSTALL_MATT=1

while (($#)); do
  case "$1" in
    --local-only) LOCAL_ONLY=1; INSTALL_PSTACK=0; INSTALL_CROSS_PSTACK=0; INSTALL_MATT=0 ;;
    --skip-pstack) INSTALL_PSTACK=0 ;;
    --skip-cross-runtime-pstack) INSTALL_CROSS_PSTACK=0 ;;
    --skip-matt) INSTALL_MATT=0 ;;
    -h|--help)
      printf '%s\n' "Usage: ./setup.sh [--local-only] [--skip-pstack] [--skip-cross-runtime-pstack] [--skip-matt]"
      exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
  shift
done

copy_dir() {
  local src="$1" dst="$2"
  rm -rf "$dst"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$dst"
}

install_skill_dir() {
  local src="$1" name="$2"
  copy_dir "$src" "$ROOT/.agents/skills/$name"
  copy_dir "$src" "$ROOT/.cursor/skills/$name"
  copy_dir "$src" "$ROOT/.claude/skills/$name"
}

node "$ROOT/.agents/bootstrap.mjs"
mkdir -p "$ROOT/.agents/skills" "$ROOT/.cursor/skills" "$ROOT/.claude/skills"

# .agents/skills is canonical. Copy canonical project/repository skills outward
# to harness-specific discovery directories. Upstream installs may later add
# additional runtime copies without changing the canonical project-owned files.
for dir in "$ROOT"/.agents/skills/*; do
  [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
  name="$(basename "$dir")"
  copy_dir "$dir" "$ROOT/.cursor/skills/$name"
  copy_dir "$dir" "$ROOT/.claude/skills/$name"
done

if (( LOCAL_ONLY )); then
  "$ROOT/scripts/verify-agent-setup.sh"
  exit 0
fi

command -v git >/dev/null || { echo "git required" >&2; exit 1; }
mkdir -p "$VENDOR"
: > "$LOCK.tmp"
trap 'rm -f "$LOCK.tmp"' EXIT
printf '# Generated by setup.sh. Review and commit intentionally.\n' >> "$LOCK.tmp"

clone_ref() {
  local url="$1" dst="$2" ref="$3"
  rm -rf "$dst"
  git clone --quiet "$url" "$dst"
  git -C "$dst" checkout --quiet "$ref"
}

if (( INSTALL_PSTACK )); then
  PSTACK_REPO="$VENDOR/cursor-plugins"
  clone_ref "https://github.com/cursor/plugins.git" "$PSTACK_REPO" "$PSTACK_REF"
  [[ -d "$PSTACK_REPO/pstack" ]] || { echo "pstack missing in cursor/plugins" >&2; exit 1; }

  PSTACK_COMMIT="$(git -C "$PSTACK_REPO" rev-parse HEAD)"
  CURSOR_PSTACK="$HOME/.cursor/plugins/local/pstack"
  mkdir -p "$(dirname "$CURSOR_PSTACK")"
  copy_dir "$PSTACK_REPO/pstack" "$CURSOR_PSTACK"

  printf 'pstack_official_commit=%s\n' "$PSTACK_COMMIT" >> "$LOCK.tmp"

  if [[ -d "$PSTACK_REPO/pstack/skills" ]]; then
    for dir in "$PSTACK_REPO/pstack/skills"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      copy_dir "$dir" "$ROOT/.agents/skills/$name"
      copy_dir "$dir" "$ROOT/.claude/skills/$name"
    done
  fi
fi

if (( INSTALL_CROSS_PSTACK )); then
  CROSS_REPO="$VENDOR/pstack-claude"
  clone_ref "https://github.com/michael-denyer/pstack-claude.git" "$CROSS_REPO" "$PSTACK_CROSS_REF"
  CROSS_SKILLS="$CROSS_REPO/plugins/pstack/skills"
  if [[ -d "$CROSS_SKILLS" ]]; then
    for dir in "$CROSS_SKILLS"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      [[ -e "$ROOT/.agents/skills/$name" ]] || copy_dir "$dir" "$ROOT/.agents/skills/$name"
      [[ -e "$ROOT/.claude/skills/$name" ]] || copy_dir "$dir" "$ROOT/.claude/skills/$name"
    done
  fi
  printf 'pstack_cross_runtime_commit=%s\n' "$(git -C "$CROSS_REPO" rev-parse HEAD)" >> "$LOCK.tmp"
fi

if (( INSTALL_MATT )); then
  MATT_REPO="$VENDOR/mattpocock-skills"
  clone_ref "https://github.com/mattpocock/skills.git" "$MATT_REPO" "$MATT_REF"
  selected=(codebase-design domain-modeling diagnosing-bugs research improve-codebase-architecture code-review prototype writing-for-agents handoff)

  for name in "${selected[@]}"; do
    src="$(find "$MATT_REPO" -path "$MATT_REPO/.git" -prune -o -type d -name "$name" -print -quit)"
    [[ -n "$src" && -s "$src/SKILL.md" ]] || continue
    install_skill_dir "$src" "$name"
  done

  printf 'matt_skills_commit=%s\n' "$(git -C "$MATT_REPO" rev-parse HEAD)" >> "$LOCK.tmp"
fi

mv "$LOCK.tmp" "$LOCK"
"$ROOT/scripts/verify-agent-setup.sh"
