#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR="$ROOT/.agent-vendor"
LOCK="$ROOT/.agent-deps.lock"

PSTACK_REF="${PSTACK_REF:-main}"
PSTACK_CROSS_REF="${PSTACK_CROSS_REF:-main}"
MATT_REF="${MATT_REF:-main}"

LOCAL_ONLY=0
COMPAT=0
INSTALL_PSTACK=1
INSTALL_CROSS_PSTACK=1
INSTALL_MATT=1

while (($#)); do
  case "$1" in
    --local-only) LOCAL_ONLY=1; INSTALL_PSTACK=0; INSTALL_CROSS_PSTACK=0; INSTALL_MATT=0 ;;
    --compat) COMPAT=1 ;;
    --skip-pstack) INSTALL_PSTACK=0 ;;
    --skip-cross-runtime-pstack) INSTALL_CROSS_PSTACK=0 ;;
    --skip-matt) INSTALL_MATT=0 ;;
    -h|--help)
      printf "%s\n" "Usage: ./setup.sh [--local-only] [--compat] [--skip-pstack] [--skip-cross-runtime-pstack] [--skip-matt]"
      exit 0 ;;
    *) printf "Unknown option: %s\n" "$1" >&2; exit 2 ;;
  esac
  shift
done

copy_dir() {
  local src="$1" dst="$2"
  rm -rf "$dst"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$dst"
}

install_repository_skill() {
  local src="$1" name="$2"
  if [[ -e "$ROOT/skills/$name" ]]; then
    printf "Skill name collides with the portable plugin: %s\n" "$name" >&2
    exit 1
  fi
  copy_dir "$src" "$ROOT/.agents/skills/$name"
}

install_compatibility() {
  local output_root marker dir name
  for output_root in "$ROOT/.cursor/skills" "$ROOT/.claude/skills"; do
    mkdir -p "$output_root"
    marker="$output_root/.agent-engineering-system-compat"
    : > "$marker"

    for dir in "$ROOT/skills"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      copy_dir "$dir" "$output_root/$name"
      printf "%s\n" "$name" >> "$marker"
    done

    for dir in "$ROOT/.agents/skills"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      if [[ -e "$ROOT/skills/$name" ]]; then
        printf "Skill name collides with the portable plugin: %s\n" "$name" >&2
        exit 1
      fi
      copy_dir "$dir" "$output_root/$name"
      printf "%s\n" "$name" >> "$marker"
    done
  done
}

node "$ROOT/.agents/bootstrap.mjs"

if (( LOCAL_ONLY )); then
  if (( COMPAT )); then
    install_compatibility
  fi
  "$ROOT/scripts/verify-plugin.sh"
  exit 0
fi

command -v git >/dev/null || { echo "git required" >&2; exit 1; }
mkdir -p "$VENDOR"
: > "$LOCK.tmp"
trap 'rm -f "$LOCK.tmp"' EXIT
printf "# Generated by setup.sh. Review and commit intentionally.\n" >> "$LOCK.tmp"

clone_ref() {
  local url="$1" dst="$2" ref="$3"
  rm -rf "$dst"
  git clone --quiet "$url" "$dst"
  git -C "$dst" checkout --quiet "$ref"
}

if (( INSTALL_PSTACK )); then
  PSTACK_REPO="$VENDOR/cursor-plugins"
  clone_ref "https://github.com/cursor/plugins.git" "$PSTACK_REPO" "$PSTACK_REF"
  [[ -d "$PSTACK_REPO/pstack" ]] || { echo "pstack missing in cursor/plugins" >&2; exit 1; }

  PSTACK_COMMIT="$(git -C "$PSTACK_REPO" rev-parse HEAD)"
  CURSOR_PSTACK="$HOME/.cursor/plugins/local/pstack"
  mkdir -p "$(dirname "$CURSOR_PSTACK")"
  copy_dir "$PSTACK_REPO/pstack" "$CURSOR_PSTACK"

  printf "pstack_official_commit=%s\n" "$PSTACK_COMMIT" >> "$LOCK.tmp"

  if [[ -d "$PSTACK_REPO/pstack/skills" ]]; then
    for dir in "$PSTACK_REPO/pstack/skills"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      install_repository_skill "$dir" "$name"
    done
  fi
fi

if (( INSTALL_CROSS_PSTACK )); then
  CROSS_REPO="$VENDOR/pstack-claude"
  clone_ref "https://github.com/michael-denyer/pstack-claude.git" "$CROSS_REPO" "$PSTACK_CROSS_REF"
  CROSS_SKILLS="$CROSS_REPO/plugins/pstack/skills"
  if [[ -d "$CROSS_SKILLS" ]]; then
    for dir in "$CROSS_SKILLS"/*; do
      [[ -d "$dir" && -s "$dir/SKILL.md" ]] || continue
      name="$(basename "$dir")"
      [[ -e "$ROOT/skills/$name" ]] || install_repository_skill "$dir" "$name"
      [[ -d "$ROOT/.claude/skills" ]] || mkdir -p "$ROOT/.claude/skills"
      copy_dir "$dir" "$ROOT/.claude/skills/$name"
    done
  fi
  printf "pstack_cross_runtime_commit=%s\n" "$(git -C "$CROSS_REPO" rev-parse HEAD)" >> "$LOCK.tmp"
fi

if (( INSTALL_MATT )); then
  MATT_REPO="$VENDOR/mattpocock-skills"
  clone_ref "https://github.com/mattpocock/skills.git" "$MATT_REPO" "$MATT_REF"
  selected=(codebase-design domain-modeling diagnosing-bugs research improve-codebase-architecture code-review prototype writing-for-agents handoff)

  for name in "${selected[@]}"; do
    src="$(find "$MATT_REPO" -path "$MATT_REPO/.git" -prune -o -type d -name "$name" -print -quit)"
    [[ -n "$src" && -s "$src/SKILL.md" ]] || continue
    install_repository_skill "$src" "$name"
  done

  printf "matt_skills_commit=%s\n" "$(git -C "$MATT_REPO" rev-parse HEAD)" >> "$LOCK.tmp"
fi

mv "$LOCK.tmp" "$LOCK"

if (( COMPAT )); then
  install_compatibility
fi

"$ROOT/scripts/verify-plugin.sh"
