#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const cwd = process.cwd();
const checkOnly = process.argv.includes("--check");
const catalogPath = path.join(cwd, "catalog.json");
const rulesPath = path.join(cwd, ".agents", "core", "AGENT_RULES.md");

if (!fs.existsSync(rulesPath)) {
  console.error("Missing .agents/core/AGENT_RULES.md");
  process.exit(1);
}
if (!fs.existsSync(catalogPath)) {
  console.error("Missing catalog.json");
  process.exit(1);
}

const catalog = JSON.parse(fs.readFileSync(catalogPath, "utf8"));
let hasStaleOutput = false;
const header = "<!-- GENERATED BY .agents/bootstrap.mjs. Edit .agents/, catalog.json, or plugin sources. -->\n\n";

function generated(lines) {
  return header + lines.join("\n") + "\n";
}

function writeFile(rel, content) {
  const out = path.join(cwd, rel);
  if (checkOnly) {
    if (!fs.existsSync(out) || fs.readFileSync(out, "utf8") !== content) {
      console.error(`Generated file is stale or missing: ${rel}`);
      hasStaleOutput = true;
    }
    return;
  }

  fs.mkdirSync(path.dirname(out), { recursive: true });
  if (fs.existsSync(out) && fs.readFileSync(out, "utf8") === content) return;
  fs.writeFileSync(out, content);
}

function prettyJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function pluginEntries(runtime) {
  return catalog.plugins
    .filter((entry) => entry.runtimes?.[runtime]?.kind === "plugin")
    .map((entry) => {
      const runtimeDefinition = entry.runtimes[runtime];
      const source = runtimeDefinition.source === "local"
        ? runtime === "claude"
          ? entry.path
          : { source: "local", path: entry.path }
        : runtimeDefinition.source;
      const result = {
        name: entry.name,
        source,
        description: entry.description,
      };
      if (entry.version) result.version = entry.version;
      if (entry.category) result.category = entry.category;
      return result;
    });
}

const marketplaceOwner = {
  name: catalog.owner.name,
  email: catalog.owner.email,
  url: catalog.owner.homepage,
};

writeFile(".claude-plugin/marketplace.json", prettyJson({
  name: catalog.name,
  owner: marketplaceOwner,
  metadata: {
    description: catalog.description,
  },
  plugins: pluginEntries("claude"),
}));

writeFile(".agents/plugins/marketplace.json", prettyJson({
  name: catalog.name,
  interface: {
    displayName: "Agent Starter",
  },
  plugins: pluginEntries("codex").map((entry) => ({
    ...entry,
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL",
    },
  })),
}));

writeFile("AGENTS.md", generated([
  "# Project Agent Instructions",
  "",
  "This repository is the `agent-starter` curated plugin catalog and installer.",
  "",
  "## Operating contract",
  "",
  "- Optimize for evidence, deep modules, local changes, explicit ownership, and simple behavior.",
  "- Primary reward: a small, understandable change that demonstrably solves the requested problem and leaves the system easier to change.",
  "- Instruction precedence is: user/task requirements, this contract, descendant `AGENTS.md` files, repository architecture, project documentation, then external guidance.",
  "- For non-trivial work, use installed pstack when available and read `plugins/agent-engineering-system/skills/code-quality/SKILL.md` completely before implementation.",
  "- For architecture-sensitive work, also read `plugins/agent-engineering-system/skills/semantic-architecture/SKILL.md` completely and inspect the nearest `ARCHITECTURE.md` for the affected subsystem; this catalog's cross-cutting model is the root `ARCHITECTURE.md`.",
  "- For comments, commit messages, pull requests, technical documentation, RFCs, architecture diagrams, technical specifications, and other engineering writing, read `plugins/agent-engineering-system/skills/technical-communication/SKILL.md` completely before drafting.",
  "- Use `.agents/skills/` for skills specific to maintaining this catalog; do not treat installed upstream skills as maintained plugin content.",
  "- Define the observable outcome, plan verification, implement, verify, self-review, and report evidence accurately.",
  "- Do not stop at a plan, compilation, or newly written tests, and do not claim unverified behavior.",
  "",
  "The complete repository operating policy is in `.agents/core/AGENT_RULES.md`.",
  "",
  "## Canonical layout",
  "",
  "- `catalog.json` is the canonical curated list of maintained and upstream offerings.",
  "- `plugins/` contains plugin packages maintained by this repository; `plugins/agent-engineering-system/` is the maintained engineering plugin.",
  "- Each maintained plugin has one canonical `skills/` tree. Harness manifests are metadata around those same files.",
  "- `.claude-plugin/marketplace.json` and `.agents/plugins/marketplace.json` are generated catalog views, not canonical plugin content.",
  "- `ARCHITECTURE.md` is semantic architecture state for this catalog and installer; consuming projects keep architecture documents beside their subsystems.",
  "- `.agents/skills/` contains skills specific to this repository; it must not contain copies of maintained plugin skills.",
  "- `setup.sh` installs the curated offerings into a consuming project through native harness routes where available.",
  "- `scripts/verify-catalog.sh` is the canonical local verification entry point. `scripts/verify-plugin.sh` remains a compatibility alias.",
  "",
  "## Project-specific section",
  "",
  "- Runtime: Node.js catalog generation plus POSIX shell setup and verification scripts.",
  "- Catalog: `catalog.json`; generated native views: `.claude-plugin/marketplace.json` and `.agents/plugins/marketplace.json`.",
  "- Maintained plugin: `plugins/agent-engineering-system/` with `code-quality`, `semantic-architecture`, and `technical-communication`.",
  "- Persistent architecture: root `ARCHITECTURE.md`.",
  "- Repository-specific skills: `.agents/skills/`.",
  "- Regenerate adapters: `node .agents/bootstrap.mjs`.",
  "- Verify: `./scripts/verify-catalog.sh`.",
  "- Install into a product: `./setup.sh --project /absolute/path/to/project --harness claude,codex,cursor`.",
  "- Legacy skill-only compatibility: use `./setup.sh --project ... --compat` only for a client that cannot load a native plugin.",
  "- Consuming repositories supply their own `AGENTS.md`, colocated `ARCHITECTURE.md` files, and project-specific skills.",
]));

writeFile("CLAUDE.md", generated([
  "# Agent Instructions",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "This checkout is the `agent-starter` curated catalog. Its maintained plugin source is `plugins/agent-engineering-system/`; the root `.claude-plugin/marketplace.json` is the generated Claude marketplace view.",
  "Use the catalog's maintained `agent-engineering-system` plugin for reusable `code-quality` and `semantic-architecture` skills.",
  "For comments, commit messages, pull requests, technical documentation, RFCs, architecture diagrams, technical specifications, and other engineering writing, read the complete `technical-communication` skill before drafting.",
  "Use project-local skills under `.agents/skills/` when their triggers apply.",
  "For architectural work, also use the plugin semantic-architecture skill and read the nearest `ARCHITECTURE.md` for the affected subsystem.",
]));

writeFile("GEMINI.md", generated([
  "# Agent Instructions",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "This checkout is the `agent-starter` curated catalog. Use the maintained `agent-engineering-system` plugin for reusable `code-quality` and `semantic-architecture` skills when the runtime supports it.",
  "For comments, commit messages, pull requests, technical documentation, RFCs, architecture diagrams, technical specifications, and other engineering writing, read the complete `technical-communication` skill before drafting.",
  "Use project-local skills under `.agents/skills/` when their triggers apply.",
  "For architectural work, also use the plugin semantic-architecture skill and read the nearest `ARCHITECTURE.md` for the affected subsystem.",
]));

writeFile(".cursor/rules/00-project-agents.mdc", generated([
  "---",
  "description: Canonical repository engineering instructions",
  "alwaysApply: true",
  "---",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "This repository is an `agent-starter` catalog. Use the installed `agent-engineering-system` plugin's canonical skills when Cursor has loaded it.",
  "Use installed pstack as the primary non-trivial engineering workflow when available.",
  "For comments, commit messages, pull requests, technical documentation, RFCs, architecture diagrams, technical specifications, and other engineering writing, read the complete `technical-communication` skill before drafting.",
  "For architectural work, also use the plugin semantic-architecture skill and read the nearest `ARCHITECTURE.md` for the affected subsystem.",
]));

if (checkOnly && hasStaleOutput) process.exit(1);
