#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const cwd = process.cwd();
const rulesPath = path.join(cwd, ".agents", "core", "AGENT_RULES.md");
const checkOnly = process.argv.includes("--check");

if (!fs.existsSync(rulesPath)) {
  console.error("Missing .agents/core/AGENT_RULES.md");
  process.exit(1);
}

const header = "<!-- GENERATED BY .agents/bootstrap.mjs. Edit .agents/, not this file. -->\n\n";
let hasStaleOutput = false;

function generated(lines) {
  return header + lines.join("\n") + "\n";
}

function writeFile(rel, content) {
  const out = path.join(cwd, rel);
  if (checkOnly) {
    if (!fs.existsSync(out) || fs.readFileSync(out, "utf8") !== content) {
      console.error(`Generated file is stale or missing: ${rel}`);
      hasStaleOutput = true;
    }
    return;
  }

  fs.mkdirSync(path.dirname(out), { recursive: true });
  if (fs.existsSync(out) && fs.readFileSync(out, "utf8") === content) return;
  fs.writeFileSync(out, content);
}

writeFile("AGENTS.md", generated([
  "# Project Agent Instructions",
  "",
  "This repository is the `agent-engineering-system` multi-harness engineering system.",
  "",
  "## Operating contract",
  "",
  "- Optimize for evidence, deep modules, local changes, explicit ownership, and simple behavior.",
  "- Primary reward: a small, understandable change that demonstrably solves the requested problem and leaves the system easier to change.",
  "- Instruction precedence is: user/task requirements, this contract, descendant `AGENTS.md` files, repository architecture, project documentation, then external guidance.",
  "- For non-trivial work, use installed pstack when available and read the complete reusable `code-quality` skill supplied by this system before implementation.",
  "- For architecture-sensitive work, also read the reusable `semantic-architecture` skill supplied by this system and inspect the relevant path under `.agents/architecture/`.",
  "- Use `.agents/skills/` for repository-specific skills; do not treat compatibility copies as canonical.",
  "- Define the observable outcome, plan verification, implement, verify, self-review, and report evidence accurately.",
  "- Do not stop at a plan, compilation, or newly written tests, and do not claim unverified behavior.",
  "",
  "The complete repository operating policy is in `.agents/core/AGENT_RULES.md`.",
  "",
  "## Canonical layout",
  "",
  "- `skills/` is the only canonical copy of reusable engineering skills.",
  "- `plugin.json`, `.codex-plugin/plugin.json`, and `.claude-plugin/plugin.json` are portable and harness-specific metadata for that same `skills/` tree.",
  "- `.agents/architecture/` is repository-local semantic architecture state, not a portable plugin capability.",
  "- `.agents/skills/` contains repository-specific skills.",
  "- `compat/` describes generated client compatibility outputs.",
  "- `scripts/verify-plugin.sh` is the canonical verification entry point.",
  "",
  "## Project-specific section",
  "",
  "- Runtime: Node.js bootstrap plus POSIX shell setup and verification scripts.",
  "- Package formats: root Agent Plugins 1.0 `plugin.json`, Codex `.codex-plugin/plugin.json`, and Claude `.claude-plugin/plugin.json`; all use root `skills/`.",
  "- Persistent architecture: `.agents/architecture/`.",
  "- Repository-specific skills: `.agents/skills/`.",
  "- Canonical verification: `./scripts/verify-plugin.sh`.",
  "- Legacy compatibility generation: `./setup.sh --local-only --compat` only when a client cannot load the native package.",
  "- Consuming repositories supply their own `AGENTS.md`, architecture model, and project-specific skills."
]));

writeFile("CLAUDE.md", generated([
  "# Agent Instructions",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "Use the `agent-engineering-system` Claude plugin for reusable `code-quality` and `semantic-architecture` skills.",
  "Use project-local skills under `.agents/skills/` when their triggers apply.",
  "Do not treat `.claude/skills/` as the normal source for reusable skills; it is legacy compatibility output only.",
  "For architectural work, also use the plugin semantic-architecture skill and progressively inspect `.agents/architecture/`."
]));

writeFile("GEMINI.md", generated([
  "# Agent Instructions",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "Use the reusable `code-quality` and `semantic-architecture` skills supplied by the agent-engineering-system package when available.",
  "Use project-local skills under `.agents/skills/` when their triggers apply.",
  "For architectural work, also use the plugin semantic-architecture skill and progressively inspect `.agents/architecture/`."
]));

writeFile(".cursor/rules/00-project-agents.mdc", generated([
  "---",
  "description: Canonical repository engineering instructions",
  "alwaysApply: true",
  "---",
  "",
  "Read and follow `AGENTS.md`.",
  "",
  "Use installed pstack as the primary non-trivial engineering workflow.",
  "Use the `agent-engineering-system` plugin's canonical reusable skills for detailed engineering quality constraints.",
  "For architectural work, also use its semantic-architecture skill and progressively inspect the relevant path under `.agents/architecture/`."
]));

if (checkOnly && hasStaleOutput) process.exit(1);
